In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Batting.csv')

In [3]:
df

,playerID,nameFirst,nameLast,birthYear,yearID,stint,teamID,lgID,G,AB,...,RBI,SB,CS,BB,SO,IBB,HBP,SH,SF,GIDP
0,abercda01,Frank,Abercrombie,1850,1871,1,TRO,NaN,1,4,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
1,addybo01,Bob,Addy,1842,1871,1,RC1,NaN,25,118,...,13.0,8.0,1.0,4,0.0,NaN,NaN,NaN,NaN,NaN
2,allisar01,Art,Allison,1849,1871,1,CL1,NaN,29,137,...,19.0,3.0,1.0,2,5.0,NaN,NaN,NaN,NaN,NaN
3,allisdo01,Doug,Allison,1846,1871,1,WS3,NaN,27,133,...,27.0,1.0,1.0,0,2.0,NaN,NaN,NaN,NaN,NaN
4,ansonca01,Cap,Anson,1852,1871,1,RC1,NaN,25,120,...,16.0,6.0,2.0,2,1.0,NaN,NaN,NaN,NaN,NaN
5,armstbo01,Robert,Armstrong,1850,1871,1,FW1,NaN,12,49,...,5.0,0.0,1.0,0,1.0,NaN,NaN,NaN,NaN,NaN
6,barkeal01,Al,Barker,1839,1871,1,RC1,NaN,1,4,...,2.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
7,barnero01,Ross,Barnes,1850,1871,1,BS1,NaN,31,157,...,34.0,11.0,6.0,13,1.0,NaN,NaN,NaN,NaN,NaN
8,barrebi01,Bill,Barrett,0,1871,1,FW1,NaN,1,5,...,1.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
9,barrofr01,Frank,Barrows,1844,1871,1,BS1,NaN,18,86,...,11.0,1.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
10,bassjo01,John,Bass,1848,1871,1,CL1,NaN,22,89,...,18.0,0.0,1.0,3,4.0,NaN,NaN,NaN,NaN,NaN
11,battijo01,Joe,Battin,1853,1871,1,CL1,NaN,1,3,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
12,bealsto01,Tommy,Beals,1850,1871,1,WS3,NaN,10,36,...,1.0,2.0,0.0,2,0.0,NaN,NaN,NaN,NaN,NaN
13,beaveed01,Edward,Beavens,1848,1871,1,TRO,NaN,3,15,...,5.0,2.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
14,bechtge01,George,Bechtel,1848,1871,1,PH1,NaN,20,94,...,21.0,4.0,0.0,2,2.0,NaN,NaN,NaN,NaN,NaN
15,bellast01,Steve,Bellan,1849,1871,1,TRO,NaN,29,128,...,23.0,4.0,4.0,9,2.0,NaN,NaN,NaN,NaN,NaN
16,berkena01,Nate,Berkenstock,1831,1871,1,PH1,NaN,1,4,...,0.0,0.0,0.0,0,3.0,NaN,NaN,NaN,NaN,NaN
17,berryto01,Tom,Berry,1842,1871,1,PH1,NaN,1,4,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
18,berthha01,Harry,Berthrong,1844,1871,1,WS3,NaN,17,73,...,8.0,3.0,1.0,4,2.0,NaN,NaN,NaN,NaN,NaN
19,biermch01,Charles,Bierman,1845,1871,1,FW1,NaN,1,2,...,0.0,0.0,0.0,1,0.0,NaN,NaN,NaN,NaN,NaN
20,birdge01,George,Bird,1850,1871,1,RC1,NaN,25,106,...,13.0,1.0,0.0,3,2.0,NaN,NaN,NaN,NaN,NaN
21,birdsda01,Dave,Birdsall,1838,1871,1,BS1,NaN,29,152,...,24.0,6.0,0.0,4,4.0,NaN,NaN,NaN,NaN,NaN
22,brainas01,Asa,Brainard,1841,1871,1,WS3,NaN,30,134,...,21.0,4.0,0.0,7,2.0,NaN,NaN,NaN,NaN,NaN
23,brannmi01,Mike,Brannock,1851,1871,1,CH1,NaN,3,14,...,0.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
24,burrohe01,Henry,Burroughs,1845,1871,1,WS3,NaN,12,63,...,14.0,0.0,0.0,1,1.0,NaN,NaN,NaN,NaN,NaN
25,careyto01,Tom,Carey,1846,1871,1,FW1,NaN,19,87,...,10.0,5.0,0.0,2,1.0,NaN,NaN,NaN,NaN,NaN
26,carleji01,Jim,Carleton,1848,1871,1,CL1,NaN,29,127,...,18.0,2.0,1.0,8,3.0,NaN,NaN,NaN,NaN,NaN
27,conefr01,Fred,Cone,1848,1871,1,BS1,NaN,19,77,...,16.0,12.0,1.0,8,2.0,NaN,NaN,NaN,NaN,NaN
28,connone01,Ned,Connor,1850,1871,1,TRO,NaN,7,33,...,2.0,0.0,0.0,0,0.0,NaN,NaN,NaN,NaN,NaN
29,cravebi01,Bill,Craver,1844,1871,1,TRO,NaN,27,118,...,26.0,6.0,3.0,3,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102786,wittgni01,Nick,Wittgren,1991,2016,1,MIA,NL,48,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102787,wolteto01,Tony,Wolters,1992,2016,1,COL,NL,71,205,...,30.0,4.0,1.0,21,53.0,2.0,0.0,4.0,0.0,1.0
102788,wongko01,Kolten,Wong,1990,2016,1,SLN,NL,121,313,...,23.0,7.0,0.0,34,52.0,2.0,9.0,0.0,5.0,3.0
102789,woodal02,Alex,Wood,1991,2016,1,LAN,NL,15,16,...,2.0,0.0,0.0,1,9.0,0.0,0.0,2.0,0.0,0.0
102790,woodbl01,Blake,Wood,1985,2016,1,CIN,NL,70,2,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102791,woodtr01,Travis,Wood,1987,2016,1,CHN,NL,81,11,...,1.0,0.0,0.0,1,5.0,0.0,0.0,0.0,0.0,0.0
102792,worleva01,Vance,Worley,1987,2016,1,BAL,AL,35,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102793,worthda01,Danny,Worth,1985,2016,1,HOU,AL,16,39,...,1.0,0.0,0.0,1,6.0,0.0,0.0,0.0,0.0,1.0
102794,wrighda03,David,Wright,1982,2016,1,NYN,NL,37,137,...,14.0,3.0,2.0,26,55.0,0.0,0.0,0.0,0.0,0.0
102795,wrighda04,Daniel,Wright,1991,2016,1,CIN,NL,4,5,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102796,wrighda04,Daniel,Wright,1991,2016,2,LAA,AL,5,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102797,wrighmi01,Mike,Wright,1990,2016,1,BAL,AL,18,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102798,wrighst01,Steven,Wright,1984,2016,1,BOS,AL,25,4,...,0.0,0.0,0.0,0,3.0,0.0,0.0,0.0,0.0,0.0
102799,yateski01,Kirby,Yates,1987,2016,1,NYA,AL,41,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102800,yelicch01,Christian,Yelich,1991,2016,1,MIA,NL,155,578,...,98.0,9.0,4.0,72,138.0,4.0,4.0,0.0,5.0,20.0
102801,ynoaga01,Gabriel,Ynoa,1993,2016,1,NYN,NL,10,3,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102802,ynoami01,Michael,Ynoa,1991,2016,1,CHA,AL,23,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102803,ynoara01,Rafael,Ynoa,1987,2016,1,COL,NL,3,5,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102804,youngch03,Chris,Young,1979,2016,1,KCA,AL,34,1,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102805,youngch04,Chris,Young,1983,2016,1,BOS,AL,76,203,...,24.0,4.0,2.0,21,50.0,0.0,3.0,0.0,0.0,4.0
102806,younger03,Eric,Young,1985,2016,1,NYA,AL,6,1,...,0.0,1.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102807,youngma03,Madison,Younginer,1990,2016,1,ATL,NL,8,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102808,zastrro01,Rob,Zastryzny,1992,2016,1,CHN,NL,8,3,...,0.0,0.0,0.0,0,2.0,0.0,0.0,0.0,0.0,0.0
102809,zieglbr01,Brad,Ziegler,1979,2016,1,ARI,NL,36,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102810,zieglbr01,Brad,Ziegler,1979,2016,2,BOS,AL,33,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0
102811,zimmejo02,Jordan,Zimmermann,1986,2016,1,DET,AL,19,4,...,0.0,0.0,0.0,0,2.0,0.0,0.0,1.0,0.0,0.0
102812,zimmery01,Ryan,Zimmerman,1984,2016,1,WAS,NL,115,427,...,46.0,4.0,1.0,29,104.0,1.0,5.0,0.0,6.0,12.0
102813,zobribe01,Ben,Zobrist,1981,2016,1,CHN,NL,147,523,...,76.0,6.0,4.0,96,82.0,6.0,4.0,4.0,4.0,17.0
102814,zuninmi01,Mike,Zunino,1991,2016,1,SEA,AL,55,164,...,31.0,0.0,0.0,21,65.0,0.0,6.0,0.0,1.0,0.0
102815,zychto01,Tony,Zych,1990,2016,1,SEA,AL,12,0,...,0.0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
playerCareerTotals = df.groupby("playerID")

In [5]:
playerCareerTotals